CREATE DATABASE IF NOT EXISTS `ut3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `ut3`;
CREATE TABLE `ut3`.`users` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `name` VARCHAR(30) NOT NULL , `surname` VARCHAR(50) NOT NULL , `tel` VARCHAR(30) NULL , `email` VARCHAR(80) NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;